language: python

python:
  - "3.7.4"
  - "3.8-dev"

dist: xenial

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -e .[cache,docs,tests]

script: >
  pytest
  -rfE
  --cov pandasdmx --cov-report term-missing

after_success:
  - coverage combine
  - codecov

notifications:
  email: false
